### PR TITLE
Back-end with runtime part

### PR DESCRIPTION
**Pull request by stebranchi**
There are a lot of new stuff, so if you don't understand something i will try to explain why i did in that way and what i wanted to do.
Stefano

### CODE REVIEW

**Comment by TKasekamp** [comment]
I have to set some code standards, otherwise this project would be complete anarchy.
First add your eclipse settings and other config files to .gitignore. That shouldn't be in the code repo.
Second the 3 million lines added is way way too much. I have tried to limit the XML file length to keep the project manageable. Please remove all but 1 of those BPMN challenge files as they really arent that needed for development. If you do need them just put them in some other folder outside this repo.

Third, are the Redis files like supervisord.conf.save really needed?

**Comment by stebranchi** [comment]
I know there is too much code, infact is not finished yet. At the beggining I was insicure on what to do so I added code instead of changing yours. The aim of this pull request is to have the same fix to issues. At the moment for me is important to have something that works and move on to the front-end. When I will have a working UI I will clear the code to let it be manageable. And i completed forgot about the .gitignore, sorry. For the third one the answer is no.

**Comment by stebranchi** [comment]
By the way the 3 millions line are there because i saved all the models and the BPI logs also

**Comment by TKasekamp** [comment]
.travis.yml is actually important. Automated tests cant run without it. Add it back and fix the errors.

**Comment by stebranchi** [comment]
I put it back but I don't understand why yesterday everything worked fine and now not

**Comment by TKasekamp** [comment]
Seems to be ` ImportError: cannot import name 'imap'`

**Comment by TKasekamp** [comment]
I can't really merge without this build being fixed. Automated tests are what keep this project working.

**Comment by stebranchi** [comment]
I know, but I can't understand why it worked yesterday, and not today. I didn't change anyhting, I only deleted models and logs from folders

**Comment by stebranchi** [comment]
Ok, imap problem is solved, now i have to change all the tests to let them work with my code

**Comment by TKasekamp** [comment]
I recommend that you do further development in branches on this repository because the automated testing is already set up. When you need to present it then you can fork it under your own name.

**Comment by stebranchi** [comment]
There is one last test that doesn't work, I'm trying to fix it

**Comment by stebranchi** [comment]
There is one test where It compare results of next_Activity that sometimes works and sometimes not, so I think it's a problem of the model he creates with scikit_learn functions, can I comment the line where results are compared?

**Comment by TKasekamp** [comment]
If the tests results are inconsistent then try to match at least part of the results. If even that is unreliable then match that there is **something** in the result. The aim of the calculation tests is to make sure everything works end-to-end.

**Comment by stebranchi** [comment]
In my opinion the problem is that with a training set with 4 entry the program can't create a precise model, so sometimes it will creates the right model that give that resultset, and othertimes create a slightly different model that is not correct for the results you want

**Comment by TKasekamp** [comment]
Are the binary files all needed?

**Comment by stebranchi** [comment]
Which binary files? I think the only thing i can remove is the folder src/
All the rest is needed. Now i'm going to remove that folder

**Comment by TKasekamp** [comment]
Can't the files in model_cache be generated automatically? If so can it be .gitignored? I'd rather not have them in the repo. But if they really are needed then that is the final thing.

**Comment by stebranchi** [comment]
They are needed for the travis testing, because when it does the training part it doesn't phisically create models, but when it has to load them he can't reach the path, so I was thinking we can leave there only the few models needed for the testing but anyways starting to ignore that folder

**Comment by TKasekamp** [comment]
Well remove what you can to keep it minimal. If you can't then I'll merge the PR.

**Comment by stebranchi** [comment]
I think i can't remove more than this

**Pull request merged**
